POST http://localhost:8080/log-in
Content-Type: application/json

{
    "email":"email1",
    "password":"password1"
}

###

POST http://localhost:8080/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzU1NzI5MzQsImV4cCI6MTczNTU3MzgzNH0.IhyKSywhulXKi95OE7setCaUqxuZfTO2Cu9y9-QNTVA
Content-Type: application/json

{
    "email": "email1",
}